### ISSUE TITLE
출발 허브와 도착 허브가 같은 경우 배송 가능 오류

### ISSUE THREAD

**Issue by re-mora** [fulflix/fulflix#79]
![image](https://github.com/user-attachments/assets/d625ab19-ca0b-4390-b7e4-24ecd5482460)

![image](https://github.com/user-attachments/assets/bf160d80-5df5-47c2-a576-768d1564429a)

**Comment by jjong52** [comment]
같은 지역에서 주문하고 배송하는 경우도 있으니 이건 가능해야 되지 않을까요?

**Comment by re-mora** [comment]
아하 제가 거기까지 생각을 못했네요!! 이슈 종료할게요!
